### ISSUE TITLE
关于Big sur的CFG解锁

### ISSUE THREAD

**Issue by sti1l-0** [sunmousn/OMEN-by-HP-Laptop-15-dc0xxx#2]
目前在Big sur下无法通过hackintool判断cfg是否解锁，那能否通过观察电源管理来判断CFG是否解锁成功呢？
如果解锁成功，在暗影精灵4上会有什么方便辨别的特征吗

**Comment by sunmousn** [comment]
可以看下这篇文章https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock

**Comment by sti1l-0** [comment]
> 可以看下这篇文章https://dortania.github.io/OpenCore-Post-Install/misc/msr-lock.html#what-is-cfg-lock

谢谢🙏
