### ISSUE TITLE
无法正常睡眠

### ISSUE THREAD

**Issue by MxFly** [sunmousn/OMEN-by-HP-Laptop-15-dc0xxx#3]
点击睡眠按钮，键盘灯熄灭后又重新点亮，已解锁cfg

**Comment by sunmousn** [comment]
是的，睡眠点亮屏幕后过几秒还会卡死机，目前在寻找解决方法

**Comment by MxFly** [comment]
嗯嗯，感谢带佬回复。
拔掉电源 单独用电池 休眠是好的。插入电源就无法睡眠了

**Comment by sunmousn** [comment]
几乎用不到睡眠，不说我都不知道哈哈
