### ISSUE TITLE
怎样屏蔽独显和启用核显

### ISSUE THREAD

**Issue by DayoWong0** [sunmousn/OMEN-by-HP-Laptop-15-dc0xxx#8]
大佬您好，我用的也是暗影精灵4 CPU和你的相同 显卡是1060，用你的EFI配置跑进度条一会就黑屏。我自己根据[Opencore Install Guide](https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/coffee-lake.html)操作了，现在安装上了系统，显卡不知道怎么驱动，bios里没有开启核显的选项，开机使用的Nvidia的显卡。请问下怎样像你这样屏蔽独显启用核显，或者麻烦您给点参考文章，谢谢

**Comment by sunmousn** [comment]
1060版的好像没有核心显卡吧，只能安装 macOS High Sierra (10.13) 版本。

**Comment by DayoWong0** [comment]
> 1060版的好像没有核心显卡吧，只能安装 macOS High Sierra (10.13) 版本。

好的 谢谢。已经安装上了10.13版本
